# Browser settings: chrome, firefox, edge
browser = chrome

# Application URLs
url = https://eventhub.rahulshettyacademy.com/login

username = samwilson33@gmail.com
password = Samwilson@123

# Framework Execution Timeouts (in seconds)
implicit.wait=10
explicit.wait=15

# Execution Mode
headless=false